# TODO: add papers by configuration file
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "zzhbrr"
repo_name: "mlsys-arxiv-daily"
show_authors: True
show_links: True
show_badge: True
max_results: 10

publish_readme: True
publish_gitpage: True
publish_wechat: False

# file paths
json_readme_path: './docs/cv-arxiv-daily.json'
json_gitpage_path: './docs/cv-arxiv-daily-web.json'
json_wechat_path: './docs/cv-arxiv-daily-wechat.json'

md_readme_path: 'README.md'
md_gitpage_path: './docs/index.md'
md_wechat_path: './docs/wechat.md'

# keywords to search
keywords:
    "LLM inference": 
        filters: ["LLM inference", "LLM inference system", "LLM serving", "Large Language Model Serving", "Large Language Model Inference"]
    "LLM Scheduling":
        filters: ["LLM Scheduling", "Large Language Model Scheduling"]
    "MoE":
        filters: ["MoE", "Mixture of experts"]
    "Speculative Decoding":
        filters: ["Speculative Inference", "Speculation", "Speculative Decoding", "Speculative Sampling"]
    "Multimodal System":
        filters: ["Diffusion inference", "Diffusion serving", "VLM Inference", "Vision-Language Models Inference"]
    
